In [237]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import default_rng


#This class is used for colors in the command prompt

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[36m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

arraySizeX = 0
arraySizeY = 0

#Asking user the size of maze they want (Along then down)

print("How long is the width of your array?")
arraySizeX = int(input())


print("How long is the height of your array?")
arraySizeY = int(input())


rng = default_rng()
randomArray = rng.integers(0, 10 , (arraySizeY,arraySizeX), )
currentElement = 0

#Defining a function which prints out the array with a chosen element to be highlighted

def printArray(arrayx,arrayy,array,currentElement):
    for x1 in range(arrayx):
        print("")
        for y1 in range(arrayy):
            if(x1 == currentElement//arrayx and y1 == currentElement % arrayx):
                print("\033[91m" + str(array[x1][y1])  + "\033[0m" , end = ' ')
            else:
                print(array[x1][y1], end = ' ')

#Printing array

printArray(arraySizeY,arraySizeX,randomArray,currentElement)





How long is the width of your array?
How long is the height of your array?

5 3 1 
0 9 6 

# Nearest neighbour (only in the direction of right and down)

In [51]:
def neighbor():
    path = []
    currentNode = 0
    length = 0
    while (currentNode != (arraySizeX*arraySizeY - 1)):
        s = abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode+arraySizeX)//arraySizeX][(currentNode+arraySizeX) % arraySizeX]))
        d = abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode + 1)//arraySizeX][(currentNode + 1) % arraySizeX]))
        if (currentNode%arraySizeX < (arraySizeX - 1) and currentNode//arraySizeX < (arraySizeY - 1)):
            if (s < d):
                currentNode += arraySizeX
                length += s
            else:
                currentNode += 1
                length += d
        elif(currentNode%arraySizeX < (arraySizeX - 1)):
            currentNode += 1
            length += d
        else:
            currentNode += arraySizeX
            length += s
        path.append(currentNode)
    path.append(currentNode)
    print(path)

    for y1 in range(arraySizeY):
            print("")
            for x1 in range(arraySizeX):
                check = 0
                for scan in range(len(path)-1):
                    if(path[scan] == x1+(y1*arraySizeX)):
                        print("\033[91m" + str(randomArray[y1][x1])  + "\033[0m" , end = ' ')
                        check = 1
                if(check == 0):
                    print(str(randomArray[y1][x1]) , end = ' ')
    
    print("\nThe length: ", length)
print(arraySizeX*arraySizeY - 1)
neighbor()
    

24
[1, 6, 7, 8, 13, 18, 19, 24, 24]

3 3 1 8 0 
7 2 2 6 8 
3 0 7 5 7 
8 6 9 5 6 
1 9 0 4 4 
The length:  9


# Dijkstra

In [52]:
#Dijkstra's algorithm

def dijkstra():

    currentNode = 0
    map = np.zeros((arraySizeX*arraySizeY,2,1))

    map[0][1] = 1

    def checkState(map):
        for x1 in range(0,arraySizeX*arraySizeY):
                if (map[x1][1] == 0):
                    return False    
        return True

    def findNextNode(map):
        min = 10000000000
        findingNode = 0
        for x in range(arraySizeX*arraySizeY):
            if (map[x][1] == 1):
                try:

                    if (map[x+1][1] == 0 and map[x+1][0] <= min):
                        min = map[x+1][0]
                        findingNode = x+1
                except:
                    pass
                try:
                    if (map[x-1][1] == 0 and map[x-1][0] <= min):
                        min = map[x-1][0]
                        findingNode = x-1
                except:
                    pass
                try:

                    if (map[x + arraySizeX][1] == 0 and map[x+ arraySizeX][0] <= min):
                        min = map[x + arraySizeX][0]
                        findingNode = x + arraySizeX
                except:
                    pass
                try:

                    if (map[x - arraySizeX][1] == 0 and map[x - arraySizeX][0] <= min):
                        min = map[x - arraySizeX][0]
                        findingNode = x - arraySizeX
                except:
                    pass
        return findingNode

    currentNode = 0

    def calculateD(direction,currentNode):
        if(direction == "w"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode-arraySizeX)//arraySizeX][(currentNode-arraySizeX) % arraySizeX]))
        elif(direction == "s"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode+arraySizeX)//arraySizeX][(currentNode+arraySizeX) % arraySizeX]))
        elif(direction == "a"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode - 1)//arraySizeX][(currentNode - 1) % arraySizeX]))
        elif(direction == "d"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode + 1)//arraySizeX][(currentNode + 1) % arraySizeX]))


    for change in range(1,arraySizeX*arraySizeY):
        map[change][0] = 999

    while (checkState(map) != True):
        map[currentNode][1] = 1
        if (currentNode >=arraySizeX):
            if (map[currentNode - arraySizeX][1] != 1 and (map[currentNode][0] + calculateD("w",currentNode) < map[currentNode - arraySizeX][0])):
                map[currentNode - arraySizeX][0] = map[currentNode][0] + calculateD("w",currentNode)
        if (currentNode//arraySizeX < (arraySizeY - 1)):
            if (map[currentNode + arraySizeX][1] != 1 and (map[currentNode][0] + calculateD("s",currentNode) < map[currentNode + arraySizeX][0])):
                map[currentNode + arraySizeX][0] = map[currentNode][0] + calculateD("s",currentNode)

        if (currentNode%arraySizeX > 0):
            if (map[currentNode - 1][1] != 1 and (map[currentNode][0] + calculateD("a",currentNode) < map[currentNode - 1][0])):
                map[currentNode - 1][0] = map[currentNode][0] + calculateD("a",currentNode)
        
        if (currentNode%arraySizeX < (arraySizeX - 1)):
            if (map[currentNode + 1][1] != 1 and (map[currentNode][0] + calculateD("d",currentNode) < map[currentNode + 1][0])):
                map[currentNode + 1][0] = map[currentNode][0] + calculateD("d",currentNode)

        currentNode = findNextNode(map)

    def checkPop(number, poparray):
        for x in poparray:
            if(x == number):
                return True
        return False

    def printSolution(arrayx,arrayy,map):
        for x1 in range(0,arrayy):
            print("")
            for y1 in range(0,arrayx):
                print(str(map[y1+(x1*arrayx)][0]) , end = ' ')

        traversal = arrayx*arrayy - 1
        nodesThatWePassed = [arrayx*arrayy - 1]

        lastDirection = 1
        popList = []
        lastDirection1 = ""
        while (traversal != 0):
            try:
                if (abs(map[traversal][0] - map[traversal - 1][0]) == calculateD("a",traversal) and map[traversal][0] >= map[traversal - 1][0] and traversal %arrayx > 0 and checkPop(traversal-1,popList) == False and lastDirection1 != "d"):
                    traversal = traversal - 1
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "a"
                    lastDirection += 1
                    if (lastDirection == arrayx*arrayy/2):
                        break
                elif (abs(map[traversal][0] - map[traversal - arrayx][0]) == calculateD("w",traversal) and map[traversal][0] >= map[traversal - arrayx][0] and traversal >=arrayx and checkPop(traversal- arrayx,popList) == False and lastDirection1 != "s"):
                    traversal -= arrayx
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "w"
                elif (abs(map[traversal][0] - map[traversal + 1][0]) == calculateD("d",traversal) and map[traversal][0] >= map[traversal + 1][0] and (traversal % arrayx) < arrayx - 1 and checkPop(traversal + 1,popList) == False and lastDirection1 != "a"):
                    traversal = traversal + 1
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "d"
                elif (abs(map[traversal][0] - map[traversal + arrayx][0]) == calculateD("s",traversal) and map[traversal][0] >= map[traversal + arrayx][0] and (traversal // arrayx) < arrayy -1 and checkPop(traversal + arrayx,popList) == False and lastDirection1 != "w"):
                    traversal = traversal + arrayx
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "s"
                else:
                    popList.append(nodesThatWePassed.pop(len(nodesThatWePassed) - 1))             
                    traversal = nodesThatWePassed[len(nodesThatWePassed) - 1]
            except:
                    break


        print("\n")
        print(list(reversed(nodesThatWePassed)))

        for y1 in range(arrayy):
            print("")
            for x1 in range(arrayx):
                check = 0
                for scan in range(len(nodesThatWePassed)-1):
                    if(nodesThatWePassed[scan] == x1+(y1*arrayx)):
                        print("\033[91m" + str(randomArray[y1][x1])  + "\033[0m" , end = ' ')
                        check = 1
                if(check == 0):
                    print(str(randomArray[y1][x1]) , end = ' ')
        

    print("\n")
    printSolution(arraySizeX,arraySizeY,map)

# Ant Colony Optimization

In [277]:
import random
print(randomArray)
trail = np.zeros((arraySizeY*2-1,arraySizeX*2-1))
trail = trail + 1
p = 0.5
for x in range(arraySizeX):
    for y in range(arraySizeY):
        trail[y*2][x*2] = randomArray[y][x]
print(trail)

class Ants:
    def __init__(self):
        self.currentNode = 5
        self.lastDirection = "Null"
    def findRandomPath(self,arraySizeX,arraySizeY):
        while (self.currentNode != (arraySizeX*2-1)*(arraySizeY*2-1)):
            randomNumber = random.uniform(0, 1)
            if(self.currentNode >=arraySizeX*2-1 and self.lastDirection != "w"):
                self.trailSum += trail[self.currentNode-1][(self.currentNode)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode-2*(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode-2*(arraySizeX*2-1)) % array(arraySizeX*2-1)])))
            if(self.currentNode %arraySizeX*2-1 > 0 and self.lastDirection != "a"):
                self.trailSum += trail[self.currentNode][(self.currentNode-1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode - 2)//(arraySizeX*2-1)][(self.currentNode - 2) % (arraySizeX*2-1)])))
            if(self.currentNode //arraySizeX*2-1 < arraySizeY -1 and self.lastDirection != "s"):
                self.trailSum += trail[self.currentNode+1][(self.currentNode)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode+
                2*(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode+2*(arraySizeX*2-1)) % (arraySizeX*2-1)])))
            if(self.currentNode %arraySizeX*2-1 < (arraySizeX*2-1) - 1 and self.lastDirection != "d"):
                self.trailSum += trail[self.currentNode][(self.currentNode+1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode + 2)//(arraySizeX*2-1)][(self.currentNode + 2) % arraySizeX])))
            


    def test(self,arraySizeX,arraySizeY):
        print("test print: ",(self.currentNode+1)% (arraySizeX*2-1))
        randomNumber = random.uniform(0, 1)
        self.trailSum = 0
        []
        if(self.currentNode >=2*(arraySizeX*2-1) and self.lastDirection != "w"):
                self.trailSum += trail[self.currentNode-(arraySizeX*2-1)//(arraySizeX*2-1)][(self.currentNode)% (arraySizeX*2-1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode-2*(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode-2*(arraySizeX*2-1)) % array(arraySizeX*2-1)])))
        if(self.currentNode %(arraySizeX*2-1) > 0 and self.lastDirection != "a"):
                self.trailSum += trail[self.currentNode-1//(arraySizeX*2-1)][(self.currentNode-1)% (arraySizeX*2-1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode - 2)//(arraySizeX*2-1)][(self.currentNode - 2) % (arraySizeX*2-1)])))
        if(self.currentNode //(arraySizeX*2-1) < arraySizeY*2 -1 and self.lastDirection != "s"):
                self.trailSum += trail[(self.currentNode+(arraySizeX*2-1))//(arraySizeX*2-1)-1][(self.currentNode+(arraySizeX*2-1))% (arraySizeX*2-1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode+2*(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode+2*(arraySizeX*2-1)) % (arraySizeX*2-1)])))
        if(self.currentNode %(arraySizeX*2-1) < (arraySizeX*2-1) - 1 and self.lastDirection != "d"):
                self.trailSum += trail[(self.currentNode+1)//(arraySizeX*2-1)-1][(self.currentNode+1)% (arraySizeX*2-1)] * (1/abs((trail[self.currentNode//(arraySizeX*2-1)][self.currentNode % (arraySizeX*2-1)]) - (trail[(self.currentNode + 2)//(arraySizeX*2-1)][(self.currentNode + 2) % arraySizeX])))
        


trail[0][1] += 1
print(trail[0][(0+1)])
print(trail)

ant1 = Ants()
ant1.test(arraySizeX,arraySizeY)
print(ant1.trailSum)


[[5 3 1]
 [0 9 6]]
[[5. 1. 3. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 9. 1. 6.]]
2.0
[[5. 2. 3. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 9. 1. 6.]]
test print:  1


IndexError: index 3 is out of bounds for axis 0 with size 3

In [236]:
print("\nSelect an option:")
print("1) Play the board.")
print("2) Nearest neighbor solution.")
print("3) Dijkstra solution.")
print("4) Ant Colony Optimization solution")
print("5) Stop")
userOption = input()
while(userOption != "5"):
    if (userOption == "1"):
        while(currentElement != arraySizeX*arraySizeY - 1):
            print("\n?")
            usersinput = input()
            if (currentElement >=arraySizeX and usersinput == "w"):
                currentElement = currentElement - arraySizeX
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
            if (currentElement //arraySizeX < arraySizeY -1 and usersinput == "s"):
                currentElement = currentElement + arraySizeX
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
            if (currentElement %arraySizeX > 0) and usersinput == "a":
                currentElement = currentElement - 1
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)

            if (currentElement %arraySizeX < arraySizeX - 1 and usersinput == "d"):
                currentElement = currentElement + 1
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
    elif (userOption == "2"):
        neighbor()
    elif (userOption == "3"):
        dijkstra()
    print("\nWould you like to try another action?")
    userOption = input()
print("Stop")


Select an option:
1) Play the board.
2) Nearest neighbor solution.
3) Dijkstra solution.
4) Ant Colony Optimization solution
5) Stop
[32, 33, 34, 66, 67, 68, 69, 70, 71, 103, 135, 136, 168, 169, 201, 202, 234, 266, 267, 299, 300, 332, 333, 334, 366, 367, 399, 431, 432, 433, 465, 497, 529, 561, 562, 594, 595, 596, 597, 598, 630, 662, 694, 695, 696, 697, 729, 761, 793, 794, 795, 796, 797, 798, 830, 831, 863, 895, 927, 959, 991, 1023, 1023]

1 9 7 1 1 2 8 2 2 7 4 7 3 8 4 2 7 3 2 1 9 0 0 8 4 9 6 4 5 3 2 0 
7 5 8 4 3 6 5 4 9 9 7 0 2 7 4 8 6 2 1 7 4 5 9 8 8 2 3 3 9 2 9 7 
2 8 8 8 7 6 7 9 8 7 6 9 2 8 2 0 1 0 6 1 3 0 5 4 4 8 4 1 6 0 7 0 
6 2 1 9 3 5 0 9 0 4 1 5 2 1 7 9 6 1 1 4 6 4 8 8 0 0 3 0 7 6 5 0 
1 5 3 0 6 8 1 3 7 4 6 2 0 4 7 5 6 8 5 2 9 2 7 3 7 7 8 8 9 9 6 2 
6 3 9 6 5 2 1 9 6 4 9 1 8 0 8 0 1 7 1 4 7 3 5 9 1 7 0 8 0 9 0 6 
3 9 8 4 3 4 7 7 8 2 0 7 7 6 5 8 2 8 2 7 6 2 9 9 5 3 3 3 1 1 9 7 
5 8 0 1 5 4 2 3 4 5 0 3 5 4 0 6 2 6 9 0 2 1 5 3 5 3 4 4 7 2 8 8 
9 3 3 7 5 0 3 8 7 6 0 6 7 4 5 2 1 7 