In [2]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import default_rng

#This class is used for colors in the command prompt

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[36m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

arraySizeX = 0
arraySizeY = 0

#Asking user the size of maze they want (Along then down)

print("How long is the width of your array?")
arraySizeX = int(input())


print("How long is the height of your array?")
arraySizeY = int(input())

#Creating a array of random numbers.

randomArray = np.random.randint(1,10,size=(arraySizeY,arraySizeX))
currentElement = 0

#Defining a function which prints out the array with a chosen element to be highlighted

def printArray(arrayx,arrayy,array,currentElement):
    for x1 in range(arrayx):
        print("")
        for y1 in range(arrayy):
            if(x1 == currentElement//arrayx and y1 == currentElement % arrayx):
                print("\033[91m" + str(array[x1][y1])  + "\033[0m" , end = ' ')
            else:
                print(array[x1][y1], end = ' ')

#Printing array

printArray(arraySizeY,arraySizeX,randomArray,currentElement)





How long is the width of your array?
How long is the height of your array?

8 1 1 4 
7 4 8 9 
1 3 1 8 
2 5 5 2 

# Nearest neighbour (only in the direction of right and down)

In [40]:
def neighbor():

    #Creating variables for the nearest neighbor.

    path = []
    currentNode = 0
    length = 0

    #While loop stops when the function has reached the destination (the bottom right node).

    while (currentNode != (arraySizeX*arraySizeY - 1)):

        #Calculating the absolute difference between the node we are current on and the adjacent bottom and right node.
        #The position of the current node can be represent as a number,
        #Where the number represents the position of the node as if the array was single vector.
        #The value can be converted to the position in the 2d array by using div and mod respectively.
        #We will be using this throughout all 3 solutions.


        #The adjacent bottom node is the size of the "x axis" away from the current node if represented as a single vector.
        #Therefore we can represent the node below as currentNode+arraySizeX
        #And the node to the right is currentNode+1

        #s and d represent the direction (wasd)

        s = abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode+arraySizeX)//arraySizeX][(currentNode+arraySizeX) % arraySizeX]))
        d = abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode + 1)//arraySizeX][(currentNode + 1) % arraySizeX]))

        #If statement is used to see if the node is on the 'edge' of the array.

        if (currentNode%arraySizeX < (arraySizeX - 1) and currentNode//arraySizeX < (arraySizeY - 1)):
            if (s < d):
                currentNode += arraySizeX
                length += s
            else:
                currentNode += 1
                length += d

        #A problem with this solution is that it priorities going right than down if the two nodes are the same number.
        #This could potentially affect the outcome of the final length.

        #These next two else if statements are used if the current node are on the 'edge' of the array.

        elif(currentNode%arraySizeX < (arraySizeX - 1)):
            currentNode += 1
            length += d

        else:
            currentNode += arraySizeX
            length += s

        #Record the nodes we have passed through.

        path.append(currentNode)
    

    path.append(currentNode)
    print(path)


    #This is used to print out the solution of the problem and is not part of the algorithm.
    #Mainly used to show a clearer solution by adding colour.

    for y1 in range(arraySizeY):
            print("")
            for x1 in range(arraySizeX):
                check = 0
                for scan in range(len(path)-1):
                    if(path[scan] == x1+(y1*arraySizeX)):
                        print("\033[91m" + str(randomArray[y1][x1])  + "\033[0m" , end = ' ')
                        check = 1
                if(check == 0):
                    print(str(randomArray[y1][x1]) , end = ' ')
    
    # Print out the final length of the solution
    print("\nThe length: ", length)
    

8
[1, 2, 5, 8, 8]

6 5 6 
7 4 1 
5 3 4 
The length:  10


# Dijkstra

In [9]:
import timeit
#Dijkstra's algorithm
def dijkstra():
    tic = timeit.default_timer()
    currentNode = 0

    #Creating a mapping system for each node in the matrix.
    #First value represents the shortest length currently to that node from the start.
    #Second value tells us if we have found the shorest length where 1 represents true.

    map = np.zeros((arraySizeX*arraySizeY,2,1))

    #The starting node is already at the shortest length (0) so mark it 1 (true).

    map[0][1] = 1

    #Before we start the algorithm, we are making the current shortest length in the map equal to a really high number which will be eventually overwritten.

    for change in range(1,arraySizeX*arraySizeY):
        map[change][0] = 999

    #This function checks if we have found the shortest route for all the nodes in the matrix.
    #returns false if no.

    def checkState(map):
        for x1 in range(0,arraySizeX*arraySizeY):
                if (map[x1][1] == 0):
                    return False    
        return True

    #After finding the shortest route for one node, we need to find the next node to work on.

    def findNextNode(map):
        min = 10000000000
        findingNode = 0
        currentNode = 0
        #For loop to check every node.

        for x in range(arraySizeX*arraySizeY):
            
            #If statements to find the next node that has the current shortest route marked and with no true marked as well.
            #The try statements are used if the node we are looking for is out of bounds, so we ignore it.

            if (map[x][1] == 1):
                try:

                    if (map[x+1][1] == 0 and map[x+1][0] <= min):
                        min = map[x+1][0]
                        findingNode = x+1
                except:

                    pass


                try:
                    if (map[x-1][1] == 0 and map[x-1][0] <= min):
                        min = map[x-1][0]
                        findingNode = x-1
                except:

                    pass


                try:

                    if (map[x + arraySizeX][1] == 0 and map[x+ arraySizeX][0] <= min):
                        min = map[x + arraySizeX][0]
                        findingNode = x + arraySizeX
                except:

                    pass


                try:

                    if (map[x - arraySizeX][1] == 0 and map[x - arraySizeX][0] <= min):
                        min = map[x - arraySizeX][0]
                        findingNode = x - arraySizeX
                except:

                    pass
        
        #return the node we have found.
        return findingNode

    #This function is used to calculate the difference between the current node and the adjacent nodes.
    #Directions are represented by "wasd" which are top, left, down, right respectively.
    #Using something similar to the nearest neighbor algorithm, we are converting a value that represents a value in a vector to a value in an array.
    #Using div and mod.

    def calculateD(direction,currentNode):

        if(direction == "w"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode-arraySizeX)//arraySizeX][(currentNode-arraySizeX) % arraySizeX]))
        elif(direction == "s"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode+arraySizeX)//arraySizeX][(currentNode+arraySizeX) % arraySizeX]))
        elif(direction == "a"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode - 1)//arraySizeX][(currentNode - 1) % arraySizeX]))
        elif(direction == "d"):
            return abs((randomArray[currentNode//arraySizeX][currentNode % arraySizeX]) - (randomArray[(currentNode + 1)//arraySizeX][(currentNode + 1) % arraySizeX]))

    #While loop to check if we have found the shortest route for all the nodes in the matrix.

    while (checkState(map) != True):

        #Current node is marked 1 as we have found the shortest path to it.

        map[currentNode][1] = 1

        #Updating any adjacent nodes if we have found a shorter route to it than the current one.

        if (currentNode >=arraySizeX):
            if (map[currentNode - arraySizeX][1] != 1 and (map[currentNode][0] + calculateD("w",currentNode) < map[currentNode - arraySizeX][0])):
                map[currentNode - arraySizeX][0] = map[currentNode][0] + calculateD("w",currentNode)
        if (currentNode//arraySizeX < (arraySizeY - 1)):
            if (map[currentNode + arraySizeX][1] != 1 and (map[currentNode][0] + calculateD("s",currentNode) < map[currentNode + arraySizeX][0])):
                map[currentNode + arraySizeX][0] = map[currentNode][0] + calculateD("s",currentNode)

        if (currentNode%arraySizeX > 0):
            if (map[currentNode - 1][1] != 1 and (map[currentNode][0] + calculateD("a",currentNode) < map[currentNode - 1][0])):
                map[currentNode - 1][0] = map[currentNode][0] + calculateD("a",currentNode)
        
        if (currentNode%arraySizeX < (arraySizeX - 1)):
            if (map[currentNode + 1][1] != 1 and (map[currentNode][0] + calculateD("d",currentNode) < map[currentNode + 1][0])):
                map[currentNode + 1][0] = map[currentNode][0] + calculateD("d",currentNode)

        #Find the next shortest node marked that hasn't been marked.

        currentNode = findNextNode(map)

    #Everything below is used to find the path to take when going from the start to finish.

    #Sometimes when finding the path, we go the wrong way because two adjacent values could be the same so we need to go backwards.
    #Therefore we need to pop values and record that we have visited that value.
    #The recording makes sure we never go there again.

    def checkPop(number, poparray):
        for x in poparray:
            if(x == number):
                return True
        return False

    #This functions find the path from the end to the beginning of the matrix as dijksras works backwards after finding the shortest distance from start to finish.  

    def printSolution(arrayx,arrayy,map):

        #Here for fun we print out the shortest distance possible from each node to the beginning
        #This isn't part of the algorithm.

        print("Shortest distance from beginning to each node.")

        for x1 in range(0,arrayy):
            print("")
            for y1 in range(0,arrayx):
                print(str(map[y1+(x1*arrayx)][0]) , end = ' ')

        #Here we mark the currentNode we are on as 'traversal' as we are going backwards to the beginning.
        #nodesThatWeHave passed records the nodes that we have passed.

        traversal = arrayx*arrayy - 1
        nodesThatWePassed = [arrayx*arrayy - 1]
        popList = []
        lastDirection1 = ""

        #While that is stopped when we have reached the beginning of the matrix.

        while (traversal != 0):
            try:

                #Here we are using a lot of conditions to make sure we reach the end with the most optimal route.
                #First of all, we are making sure that the different between the adjacent nodes are the same as the difference between the adjacent nodes in the 'map'
                #This assures us that we are going the right way.

                #Secondly, we making sure the condition above is true when the current node we are on is bigger than the adjacent node.

                #Thirdly, we need to make sure that we are not going of the edge of the matrix.

                #Then we check if we have went to a node that we have already visited.
                #The visited node happens because the if statements below priorities going left,up,down then right.
                #There are cases when the adjacent nodes are the same values, so we need to go backwards just in case we are going the wrong way.

                #Lastly, we cant go back to a node that we just visited.

                #With all these conditions, we are able to find the most optimal route from the beginning to end.

                if (abs(map[traversal][0] - map[traversal - 1][0]) == calculateD("a",traversal) and map[traversal][0] >= map[traversal - 1][0] and traversal %arrayx > 0 and checkPop(traversal-1,popList) == False and lastDirection1 != "d"):
                    
                    #below every if statement we are adding the node to the list and updating the current node.

                    traversal = traversal - 1
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "a"

                elif (abs(map[traversal][0] - map[traversal - arrayx][0]) == calculateD("w",traversal) and map[traversal][0] >= map[traversal - arrayx][0] and traversal >=arrayx and checkPop(traversal- arrayx,popList) == False and lastDirection1 != "s"):

                    traversal -= arrayx
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "w"

                elif (abs(map[traversal][0] - map[traversal + 1][0]) == calculateD("d",traversal) and map[traversal][0] >= map[traversal + 1][0] and (traversal % arrayx) < arrayx - 1 and checkPop(traversal + 1,popList) == False and lastDirection1 != "a"):

                    traversal = traversal + 1
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "d"

                elif (abs(map[traversal][0] - map[traversal + arrayx][0]) == calculateD("s",traversal) and map[traversal][0] >= map[traversal + arrayx][0] and (traversal // arrayx) < arrayy -1 and checkPop(traversal + arrayx,popList) == False and lastDirection1 != "w"):

                    traversal = traversal + arrayx
                    nodesThatWePassed.append(traversal)
                    lastDirection1 = "s"

                else:
                    
                    #This else statement is used if the first condition is not met.
                    #We go back in time to try again on a different node.

                    popList.append(nodesThatWePassed.pop(len(nodesThatWePassed) - 1))             
                    traversal = nodesThatWePassed[len(nodesThatWePassed) - 1]
            except:
                    break


        print("\n")

        #The list we have created was from end to beginning so we reverse the list to get beginning to end.

        print(list(reversed(nodesThatWePassed)))

        #This is not part of the algorithm, just to print out the solution with colours.

        for y1 in range(arrayy):
            print("")
            for x1 in range(arrayx):
                check = 0
                for scan in range(len(nodesThatWePassed)-1):
                    if(nodesThatWePassed[scan] == x1+(y1*arrayx)):
                        print("\033[91m" + str(randomArray[y1][x1])  + "\033[0m" , end = ' ')
                        check = 1
                if(check == 0):
                    print(str(randomArray[y1][x1]) , end = ' ')
        
    #Call the functions within the function
    #Tic tok used to time how long the processing time was.

    print("\n")
    printSolution(arraySizeX,arraySizeY,map)
    toc = timeit.default_timer()
    print(toc - tic)

# Ant Colony Optimization

In [166]:
import timeit
from random import random
from random import randint
print(randomArray)
trail = np.zeros((arraySizeY*2-1,arraySizeX*2-1))
trail = trail + 1
p = 0.5
for x in range(arraySizeX):
    for y in range(arraySizeY):
        trail[y*2][x*2] = randomArray[y][x]
print(trail)

class Ants:
    def __init__(self):
        self.currentNode = 0
        self.lastDirection = "Null"

    def updateCurrentNode(self,character,arraySizeX):
        if character == "w":
            return (-2*(arraySizeX*2-1))
        elif character == "a":
            return -2
        elif character == "s":
            return (2*(arraySizeX*2-1))
        elif character == "d":
            return +2
        return 0

    def calculateDifference(self, character):

        if character ==  "w":
            return (trail[self.ModandDiv("//")][self.ModandDiv("%")]) - (trail[(self.currentNode-2*(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode-2*(arraySizeX*2-1)) % (arraySizeX*2-1)])
        elif character == "a":
            return (trail[self.ModandDiv("//")][self.ModandDiv("%")]) - (trail[(self.currentNode - 2)//(arraySizeX*2-1)][(self.currentNode - 2) % (arraySizeX*2-1)])
        elif character == "s":
            return (trail[self.ModandDiv("//")][self.ModandDiv("%")]) - (trail[(self.currentNode + (2 * (arraySizeX*2-1)))//(arraySizeX*2-1)][(self.currentNode+(2*(arraySizeX*2-1))) % (arraySizeX*2-1)])
        elif character == "d":
            return (trail[self.ModandDiv("//")][self.ModandDiv("%")]) - (trail[(self.currentNode + 2)//(arraySizeX*2-1)][(self.currentNode + 2) % (arraySizeX*2-1)])

    def returnAdj(self, character):
        if character == "s":
            return trail[(self.currentNode+(arraySizeX*2-1))//(arraySizeX*2-1)][(self.currentNode+(arraySizeX*2-1))% (arraySizeX*2-1)]
        elif character == "d":
            return trail[(self.currentNode+1)//(arraySizeX*2-1)][(self.currentNode+1)% (arraySizeX*2-1)]
        elif character == "w":
            return trail[(self.currentNode-(arraySizeX*2-1))//(arraySizeX*2-1)][((self.currentNode)-(arraySizeX*2-1))% (arraySizeX*2-1)]
        elif character == "a":
            return trail[(self.currentNode-1)//(arraySizeX*2-1)][(self.currentNode-1)% (arraySizeX*2-1)]
        return 0


    def ModandDiv(self, symbol):
        if symbol == "//":
            return self.currentNode//(arraySizeX*2-1)
        elif symbol == "%":
            return self.currentNode % (arraySizeX*2-1)

    def moveAnt(self,i,arraySizeX):
        self.lastDirection = i
        if i == "w":
            adjNode = self.currentNode - arraySizeX*2-1
        elif i == "a":
            adjNode = self.currentNode - 1
        elif i == "s":
            adjNode = self.currentNode + arraySizeX*2-1
        elif i == "d":
            adjNode = self.currentNode + 1
        if adjNode not in self.uniqueNodes:
            self.totalLength += abs(self.calculateDifference(i))
            self.uniqueNodes.append(adjNode)
        self.currentNode += self.updateCurrentNode(i,arraySizeX)


    def findRandomPath(self,arraySizeX,arraySizeY):
        self.currentNode = 0
        self.lastDirection = "Null"
        self.totalLength = 0
        self.uniqueNodes = []
        while (self.currentNode != (arraySizeX*2-1)*(arraySizeY*2-1)-1):
            self.case = []
            specialCase = []
            self.trailSum = 0
            if ((self.currentNode //((arraySizeX*2)-1)) < (arraySizeY*2 - 2) and self.lastDirection != "w") :
                if (self.calculateDifference("s") != 0):
                    self.trailSum += self.returnAdj("s") * (1/abs(self.calculateDifference("s")))
                    self.case.append("s")
                else:
                    specialCase.append("s")
            if (self.currentNode %(arraySizeX*2-1) < (arraySizeX*2-1) - 1 and self.lastDirection != "a") :
                if (self.calculateDifference("d") != 0):
                    self.trailSum += self.returnAdj("d") * (1/abs(self.calculateDifference("d")))
                    self.case.append("d")
                else:
                    specialCase.append("d")
            if (self.currentNode >=(arraySizeX*2-1) and self.lastDirection != "s") :
                if (self.calculateDifference("w") != 0):
                    self.trailSum += self.returnAdj("w") * (1/abs(self.calculateDifference("w")))
                    self.case.append("w")
                else:
                    rn = randint(0, 1)
                    if (rn == 1):
                        specialCase.append("w")
            if (self.currentNode % (arraySizeX*2-1) > 0 and self.lastDirection != "d") :
                if (self.calculateDifference("a") != 0):
                    self.trailSum += self.returnAdj("a") * (1/abs(self.calculateDifference("a")))
                    self.case.append("a")
                else:
                    rn = randint(0, 1)
                    if (rn == 1):
                        specialCase.append("a")
            
            if len(specialCase) == 0:
                if len(self.case) == 1:
                    self.moveAnt(self.case[0],arraySizeX)
                elif len(self.case) == 2:
                    rn = random()
                    if (rn < (self.returnAdj(self.case[0]) *(1/abs(self.calculateDifference(self.case[0]))/self.trailSum))):
                        self.moveAnt(self.case[0],arraySizeX)
                    else:
                        self.moveAnt(self.case[1],arraySizeX)
                elif len(self.case) == 3:
                    rn = random()
                    if (rn < self.returnAdj(self.case[0]) *(1/abs(self.calculateDifference(self.case[0]))/self.trailSum)):
                        self.moveAnt(self.case[0],arraySizeX)
                    elif (rn < ((self.returnAdj(self.case[0])*1/abs(self.calculateDifference(self.case[0]))+(self.returnAdj(self.case[0])*1/abs(self.calculateDifference(self.case[1]))))/self.trailSum)):
                        self.moveAnt(self.case[1],arraySizeX)
                    else:
                        self.moveAnt(self.case[2],arraySizeX)
            elif len(specialCase) == 1:
                self.moveAnt(specialCase[0],arraySizeX)
            elif len(specialCase) == 2:
                if (randint(0, 1) == 0):
                    self.moveAnt(specialCase[0],arraySizeX)
                else:
                    self.moveAnt(specialCase[1],arraySizeX)  
            else:
                randomnumber = randint(0, 2)
                if (randomnumber == 0):
                    self.moveAnt(specialCase[0],arraySizeX)
                elif (randomnumber == 1):
                    self.moveAnt(specialCase[1],arraySizeX)
                else:
                    self.moveAnt(specialCase[2],arraySizeX)    
                
    def test(self,arraySizeX,arraySizeY):
        randomNumber = random.uniform(0, 1)
        self.trailSum = 0
        []
        

ant1 = Ants()
ant1.findRandomPath(arraySizeX,arraySizeY)


listOfAnts = []

tic = timeit.default_timer()
for i in range(500):
    listOfAnts.append(Ants())

def decayPhermone():
    for y in range(arraySizeY):
        for x in range(arraySizeX):
            if (x < arraySizeX-1) :
                trail[y*2][(2*x)+1] *= 0.5
            if (y < arraySizeY-1) :
                trail[y*2+1][2*x] *=0.5


def cycle(number,trail):
    for cycle in range(number):
        decayPhermone()
        for ants in listOfAnts:
            ants.findRandomPath(arraySizeX,arraySizeY)
        for ants in listOfAnts:
            for phermone in ants.uniqueNodes:
                trail[phermone//(arraySizeX*2-1)][phermone % (arraySizeX*2-1)] += (1/ants.totalLength)
        print(trail)

cycle(10,trail)

smallestLength = 99999
for ants in listOfAnts:
    ants.findRandomPath(arraySizeX,arraySizeY)
    if (ants.totalLength < smallestLength):
        smallestLength = ants.totalLength

print(smallestLength)
toc = timeit.default_timer()
print(toc - tic) 


[[3 7 2 6 2]
 [4 2 1 8 4]
 [7 5 5 4 6]
 [5 5 1 1 6]
 [1 7 4 9 7]]
[[3. 1. 7. 1. 2. 1. 6. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [4. 1. 2. 1. 1. 1. 8. 1. 4.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [7. 1. 5. 1. 5. 1. 4. 1. 6.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 1. 5. 1. 1. 1. 1. 1. 6.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 7. 1. 4. 1. 9. 1. 7.]]
[[ 3.          6.17127484  7.          5.59750033  2.          6.16191095
   6.          5.78424456  2.        ]
 [17.52562965  1.          7.2537948   1.          4.68146094  1.
   4.20800663  1.          3.39013456]
 [ 4.         11.49915773  2.          9.68540456  1.          2.70677478
   8.          4.32851863  4.        ]
 [ 9.77797619  1.          6.17568565  1.          4.83705754  1.
   3.30834632  1.          4.69300157]
 [ 7.          6.47517042  5.         11.63812774  5.         11.02571791
   4.         10.92201689  6.        ]
 [ 6.15617561  1.          6.90747178  1.          4.92301531  1.
   3.48726374  1.         13.56352339]
 [ 5.    

In [149]:
from random import randint
from random import random
value = random()
print(value)

0.4841337453886383


In [10]:
print("\nSelect an option:")
print("1) Play the board.")
print("2) Nearest neighbor solution.")
print("3) Dijkstra solution.")
print("4) Ant Colony Optimization solution")
print("5) Stop")
userOption = input()
while(userOption != "5"):
    if (userOption == "1"):
        while(currentElement != arraySizeX*arraySizeY - 1):
            print("\n?")
            usersinput = input()
            if (currentElement >=arraySizeX and usersinput == "w"):
                currentElement = currentElement - arraySizeX
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
            if (currentElement //arraySizeX < arraySizeY -1 and usersinput == "s"):
                currentElement = currentElement + arraySizeX
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
            if (currentElement %arraySizeX > 0) and usersinput == "a":
                currentElement = currentElement - 1
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)

            if (currentElement %arraySizeX < arraySizeX - 1 and usersinput == "d"):
                currentElement = currentElement + 1
                printArray(arraySizeX,arraySizeY,randomArray,currentElement)
    elif (userOption == "2"):
        neighbor()
    elif (userOption == "3"):
        dijkstra()
    print("\nWould you like to try another action?")
    userOption = input()
print("Stop")


Select an option:
1) Play the board.
2) Nearest neighbor solution.
3) Dijkstra solution.
4) Ant Colony Optimization solution
5) Stop


Shortest distance from beginning to each node.

[0.] [7.] [7.] [10.] 
[1.] [4.] [8.] [9.] 
[7.] [5.] [7.] [10.] 
[8.] [7.] [7.] [10.] 

[0, 4, 5, 9, 13, 14, 15]

8 1 1 4 
7 4 8 9 
1 3 1 8 
2 5 5 2 0.007143800000449119

Would you like to try another action?
Stop
